name: Approval workflow

on:
  pull_request_review:
    types: [submitted]
  workflow_run:
    workflows: [Cypress Tests]
    types:
      - completed

jobs:
  labelWhenApproved:
    if: ${{ steps.runCypress.outcome == 'success' }} && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
