name: Approval workflow

on:
  pull_request:
    types: [review_requested]
  workflow_run:
    workflows: [Run Cypress Tests]
    types:
      - completed

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
        if: ${{ steps.runCypress.outcome == 'success' }} && github.event.review.state == 'approved'

  automerge:
    runs-on: ubuntu-latest
    needs: runTestsAgainstPreview
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
