# name: Automerge with Approval

# on:
#   push:
#     branches:
#       - feature/*
#   pull_request:
#     types: [labeled]
#   workflow_run:
#     workflows: [Run Cypress Tests, Approval Workflow]
#     types:
#       - completed

# jobs:
#   addAutomergeLabel:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Add Automerge label
#         uses: actions-ecosystem/action-add-labels@v1
#         if: ${{ (github.event.review.state == 'approved') && (steps.runCypress.outcome == 'success')}}
#         with:
#           labels: automerge

#   automerge:
#     runs-on: ubuntu-latest
#     needs: labelWhenApproved
#     steps:
#       - id: automerge
#         name: automerge
#         uses: "pascalgn/automerge-action@v0.15.3"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#           MERGE_RETRIES: 10
#           MERGE_RETRY_SLEEP: 10000
